import { createServer } from 'vite';
import { launchChromium } from './browser.mjs';
const [out, vp = '1280x720'] = process.argv.slice(2);
const server = await createServer({ root: process.cwd(), server: { port: 0, host: '127.0.0.1' }, logLevel: 'error' });
await server.listen();
const { port } = server.httpServer.address();
const { browser } = await launchChromium();
const [w, h] = vp.split('x').map(Number);
const page = await browser.newPage({ viewport: { width: w, height: h }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: 'load', timeout: 180000 });
await page.waitForFunction(() => window.__sakura && document.querySelector('#app')?.children.length > 0, null, { timeout: 180000 });
await page.evaluate(() => { location.hash = '#/lobby'; }); await page.waitForTimeout(4000); await page.evaluate(() => { document.querySelectorAll('.modal-overlay').forEach((m) => m.remove()); location.hash = '#/student/hikari?tab=info'; });
await page.waitForTimeout(15000); console.log(await page.evaluate(() => location.hash + ' canvas=' + !!document.querySelector('#app canvas') + ' screen=' + document.querySelector('#app')?.dataset.screen));
await page.screenshot({ path: out, timeout: 180000 });
console.log('saved', out, errors.join(' | '));
await browser.close();
await server.close();
